// Data file containing items for sale

const soldItems = [];

const itemsForSale = [
  {
    id: 1,
    name: 'Bronze 5x7 Picture Frame',
    image: '/images/bronzeFrame_5x7.png',
    value: 3,
    quantity: 1,
  },
  {
    id: 2,
    name: 'starlink_ps4',
    image: '/images/starlink_ps4.png',
    value: 4,
    quantity: 1,
  },
  {
    id: 3,
    name: 'StimpyFig',
    image: '/images/StimpyFig.png',
    value: 3,
    quantity: 1,
  },
  {
    id: 4,
    name: 'Gold Matted 5x7 Picture Frame',
    image: '/images/goldFrame_5x7.png',
    value: 3,
    quantity: 1,
  },
  {
    id: 5,
    name: 'Gold Matted 5x7 Picture Frame',
    image: '/images/goldFrame_8x10.png',
    value: 4,
    quantity: 1,
  },
  {
    id: 6,
    name: 'Gold Matted 8x10 Picture Frame',
    image: '/images/goldFrame_8x10.png',
    value: 4,
    quantity: 1,
  },
  {
    id: 7,
    name: 'lightPlasticMirror',
    image: '/images/lightPlasticMirror.png',
    value: 3,
    quantity: 1,
  },
  {
    id: 8,
    name: 'puzzleBooks_3',
    image: '/images/puzzleBooks_3.png',
    value: 5,
    quantity: 1,
  },
  {
    id: 9,
    name: "St Patrick's Day Hat",
    image: '/images/stPatHat.png',
    value: 2,
    quantity: 1,
  },
  {
    id: 10,
    name: 'Silver 5x7 Matted Frame',
    image: '/images/silverFrame_5x7.png',
    value: 2,
    quantity: 1,
  },
  {
    id: 11,
    name: 'Black hangable shelf',
    image: '/images/blackShelf.png',
    value: 3,
    quantity: 1,
  },
  {
    id: 12,
    name: 'Black hexagon mirror',
    image: '/images/blackCheckeredMirror.png',
    value: 3,
    quantity: 1,
  },
  {
    id: 13,
    name: 'Checkered driving wheel cover',
    image: '/images/checkeredWheelCover.png',
    value: 2,
    quantity: 1,
  },
  {
    id: 14,
    name: 'Red driving wheel cover',
    image: '/images/redWheelCover.png',
    value: 2,
    quantity: 1,
  },
  {
    id: 15,
    name: 'Hey Arnold! Miniature Figurine',
    image: '/images/arnoldFig.png',
    value: 3,
    quantity: 1,
  },
  {
    id: 16,
    name: 'Ren Miniature Figurine',
    image: '/images/RenFig.png',
    value: 3,
    quantity: 1,
  },
  {
    id: 17,
    name: 'Wayland sherpa blanket',
    image: '/images/plushCheckeredSherpa.png',
    value: 5,
    quantity: 1,
  },
  {
    id: 18,
    name: 'Test Item 01',
    image: '/images/test_item_01.png',
    value: 1,
    quantity: 1,
  },
  {
    id: 19,
    name: 'Test Item 02',
    image: '/images/test_item_02.png',
    value: 2,
    quantity: 1,
  },
  {
    id: 20,
    name: 'Test Item 03',
    image: '/images/test_item_03.png',
    value: 3,
    quantity: 1,
  },
  {
    id: 21,
    name: 'Test Item 04',
    image: '/images/test_item_04.png',
    value: 4,
    quantity: 1,
  },
  {
    id: 22,
    name: 'Test Item 05',
    image: '/images/test_item_05.png',
    value: 5,
    quantity: 1,
  },
  {
    id: 23,
    name: 'Test Item 06',
    image: '/images/test_item_06.png',
    value: 1,
    quantity: 1,
  },
  {
    id: 24,
    name: 'Test Item 07',
    image: '/images/test_item_07.png',
    value: 2,
    quantity: 1,
  },
  {
    id: 25,
    name: 'Test Item 08',
    image: '/images/test_item_08.png',
    value: 3,
    quantity: 1,
  },
  {
    id: 26,
    name: 'Test Item 09',
    image: '/images/test_item_09.png',
    value: 4,
    quantity: 1,
  },
  {
    id: 27,
    name: 'Test Item 10',
    image: '/images/test_item_10.png',
    value: 5,
    quantity: 1,
  },
  {
    id: 28,
    name: 'Test Item 11',
    image: '/images/test_item_11.png',
    value: 1,
    quantity: 1,
  },
  {
    id: 29,
    name: 'Test Item 12',
    image: '/images/test_item_12.png',
    value: 2,
    quantity: 1,
  },
  {
    id: 30,
    name: 'Test Item 13',
    image: '/images/test_item_13.png',
    value: 3,
    quantity: 1,
  },
  {
    id: 31,
    name: 'Test Item 14',
    image: '/images/test_item_14.png',
    value: 4,
    quantity: 1,
  },
  {
    id: 32,
    name: 'Test Item 15',
    image: '/images/test_item_15.png',
    value: 5,
    quantity: 1,
  },
  {
    id: 33,
    name: 'Test Item 16',
    image: '/images/test_item_16.png',
    value: 1,
    quantity: 1,
  },
  {
    id: 34,
    name: 'Test Item 17',
    image: '/images/test_item_17.png',
    value: 2,
    quantity: 1,
  },
  {
    id: 35,
    name: 'Test Item 18',
    image: '/images/test_item_18.png',
    value: 3,
    quantity: 1,
  },
  {
    id: 36,
    name: 'Test Item 19',
    image: '/images/test_item_19.png',
    value: 4,
    quantity: 1,
  },
  {
    id: 37,
    name: 'Test Item 20',
    image: '/images/test_item_20.png',
    value: 5,
    quantity: 1,
  },
];

module.exports = {
  itemsForSale,
  soldItems
}; 
